spring.application.name=TestingApp
#DB configuration
spring.datasource.url=jdbc:mysql://mysql-spring.cw3sgeg44fxm.us-east-1.rds.amazonaws.com:3306/mysqlRDS
spring.datasource.username=root
spring.datasource.password=Sujit123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

my.variable=dev